; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dfrobot_beetle_esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags =
    -D WIFI_SSID=\"parkytown\"
    -D WIFI_PASS=\"thisismyserver\"
    -D MQTT_BROKER=\"mqtt.local\"
    -D MQTT_NAMESPACE=\"dev_kiendinhtrung\"
    -D ECONNECT_BOARD_PROFILE=\"esp8266\"
    -D ECONNECT_PROJECT_ID=\"8eda405d-fc07-40f4-89d6-e9f246e09205\"
    -D ECONNECT_SECRET_KEY=\"e037c1a6901d33e201442f75971460e5abbd27334f48e0db4ec631673ab6cdc6\"
    -D ECONNECT_DEVICE_ID=\"562533fb-2130-54b9-82a9-caba003b99ab\"
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
monitor_speed = 115200

[env:jc3827w543]
platform = espressif32
board = jc3827w543
framework = arduino
build_flags =
    -D BOARD_JC3827W543=1
    -D LV_CONF_SKIP=1
    -I src/display_ui
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
    lovyan03/LovyanGFX@^1.1.12
    lvgl/lvgl@^9.1.0
    TAMC_GT911
monitor_speed = 115200
